PROGRAM GetEnv5(INPUT, OUTPUT);
USES DOS;
BEGIN {GetEnv5}
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('QUERY STRING: ', GetEnv('QUERY_STRING'));
  WRITELN('REQUEST METHOD: ', GetEnv('REQUEST_METHOD'));
  WRITELN('CONTENT LENGTH: ', GetEnv('CONTENT_LENGTH'));
  WRITELN('HTTP USER AGENT: ', GetEnv('HTTP_USER_AGENT'));
  WRITELN('HTTP HOST: ', GetEnv('HTTP_HOST'))
END. {GetEnv5}
